<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateSmsRequestsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::disableForeignKeyConstraints();

        Schema::create('sms_requests', function (Blueprint $table) {
            $table->id();
            // $table->unsignedBigInteger('template_id');
            $table->bigInteger('template_id')->unsigned();
            $table->foreign('template_id')->references('id')->on('sms_templates');
            $table->BigInteger('reference_id')->comment('It is the reference id generated by individual project');
            $table->json('message_variables');
            $table->smallInteger('attempt_count');
            // $table->enum('status')->comment('success/failed/pending/under_process');
            $table->enum('status',['success','failed','pending','under_process'])->comment('success/failed/pending/under_process');
            $table->json('meta_data')->nullable()->default('{}');
            $table->boolean('is_notified')->default(false);
            $table->BigInteger('preferred_account_id')->nullable()->comment('When we want to trigger using particular account_id');
            // $table->enum('source')->comment('api, message_queue');
            $table->enum('source',['api','message_queue'])->comment('api, message_queue');
            $table->smallInteger('generated_message_characters')->nullable();
            $table->smallInteger('billing_count')->nullable();
            $table->BigInteger('created_by');
            // $table->unsignedBigInteger('product_id');
            $table->bigInteger('product_id')->unsigned();
            $table->foreign('product_id')->references('id')->on('products');
            // $table->unsignedBigInteger('organization_id');
            $table->bigInteger('organization_id')->unsigned();
            $table->foreign('organization_id')->references('id')->on('organizations');
            $table->index(['reference_id', 'created_by']);
        });

        Schema::enableForeignKeyConstraints();
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sms_requests');
    }
}
