<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateSmsLogsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::disableForeignKeyConstraints();

        Schema::create('sms_logs', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('request_id')->unsigned();
            $table->foreign('request_id')->references('id')->on('sms_requests');
            $table->bigInteger('template_id')->unsigned();
            $table->foreign('template_id')->references('id')->on('sms_templates');
            $table->bigInteger('vendor_account_id')->unsigned();
            $table->foreign('vendor_account_id')->references('id')->on('sms_vendor_accounts');
            $table->longText('generate_message');
            $table->enum('status',['success','failed','pending','under_process'])->comment('success/failed/pending/under_process');
            $table->string('vendor_request_id')->comment('It is the id generated by vendor');
            $table->longText('remarks');
            $table->index(['vendor_request_id', 'vendor_account_id']);
        });

        Schema::enableForeignKeyConstraints();
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sms_logs');
    }
}
